In [1]:
import numpy as np

In [2]:
list1=[12,2,3,4,1]


In [3]:
np.array(list1)

array([12,  2,  3,  4,  1])

In [4]:
ll=[[12,2,3],[4,5,6]]

In [5]:
np.array(ll)

array([[12,  2,  3],
       [ 4,  5,  6]])

In [7]:
np.arange(12,25)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
np.arange(12,25,2)

array([12, 14, 16, 18, 20, 22, 24])

In [14]:
np.zeros(12)   

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
a=np.ones((4,5))

In [19]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
a[2][1]=12

In [21]:
a

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1., 12.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [23]:
np.linspace(1,12,5)#gives 5 equal values between 1 and 12

array([ 1.  ,  3.75,  6.5 ,  9.25, 12.  ])

In [24]:
np.eye(6)#creates an identity matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

#Random functions of numpy


In [26]:
np.random.rand(3,4)# number is from 0 to 1 and 1 in not inclusive whereas 0 is inclusive

array([[0.26933828, 0.41434431, 0.21542013, 0.57828492],
       [0.69082814, 0.64163666, 0.60680613, 0.15686281],
       [0.80114518, 0.18272829, 0.63420335, 0.83765708]])

In [27]:
np.random.randn(3,4)#on a uniform distributive and mean is 0 and standard deviation is 1

array([[ 0.10655439, -0.00770354, -0.08512177, -1.215249  ],
       [-0.67512036,  1.83499932,  1.12636811,  1.02876904],
       [-1.07045507,  1.29530425, -0.53964833, -0.4946967 ]])

In [29]:
np.random.randint(12,1222)# returns a random number 

1054

In [32]:
np.random.randint(2,12,10)#creates an array of random number in given range

array([ 8,  3, 11, 11,  8,  4,  2,  6,  6, 10])

In [33]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
rand_array=np.random.randint(0,100,20)

In [35]:
rand_array

array([10, 52,  7, 40, 45, 79, 79, 49, 38, 67, 12, 95,  9, 75, 38, 18, 35,
       88, 81, 47])

In [37]:
sample_array.reshape(5,6)#5*6==30 otherwise it will give an error

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [38]:
rand_array.max()

95

In [39]:
rand_array.min()#gives the maximum value in array

7

In [40]:
rand_array.argmax()#gives the position of maximum value

11

In [41]:
sample_array.argmax()#--------

29

In [48]:
ar=sample_array.reshape(5,6)

In [49]:
ar

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [51]:
ar.T#transpose

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])